/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asuka-PC
 */
public class Frame4 extends javax.swing.JFrame {

    /**
     * Creates new form Frame4
     */
    public Frame4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eAbsen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        eNama1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnPrs = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TAHasil = new javax.swing.JTextArea();
        eNilai = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        eMapel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);
        getContentPane().add(eAbsen);
        eAbsen.setBounds(100, 80, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Formulir");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 10, 50, 14);

        jLabel8.setText("Absen");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 90, 40, 14);
        getContentPane().add(eNama1);
        eNama1.setBounds(100, 40, 140, 30);

        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 50, 40, 14);

        btnPrs.setText("OK");
        btnPrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrsActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrs);
        btnPrs.setBounds(120, 210, 47, 23);

        TAHasil.setColumns(20);
        TAHasil.setRows(5);
        jScrollPane3.setViewportView(TAHasil);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 250, 240, 120);
        getContentPane().add(eNilai);
        eNilai.setBounds(100, 160, 140, 30);

        jLabel9.setText("Nilai");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 170, 40, 14);
        getContentPane().add(eMapel);
        eMapel.setBounds(100, 120, 140, 30);

        jLabel7.setText("Mapel");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 130, 40, 14);

        getAccessibleContext().setAccessibleDescription("");

        setBounds(0, 0, 296, 429);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrsActionPerformed
        // TODO add your handling code here:
        String nama = eNama1.getText();
        String absen = eAbsen.getText();
        String mapel = eMapel.getText();
        int nilai=Integer.parseInt(eNilai.getText());
        String penilaian=null;

        if(nilai<=74)
            penilaian = "Tidak Lulus";
        
        if(nilai>=75 && nilai <=84)
            penilaian = "Lulus";
        
        if(nilai>=85 && nilai<=100)
            penilaian = "Sempurna";
        else if(nilai>100)
            penilaian = "Melebihi batas";
        
        TAHasil.setText("Nama Siswa : "+nama+"\n"+"Kelas : "+absen+"\n"+"Mapel: "+mapel+"\n"+"Nilai : "+penilaian);
    }//GEN-LAST:event_btnPrsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TAHasil;
    private javax.swing.JButton btnPrs;
    private javax.swing.JTextField eAbsen;
    private javax.swing.JTextField eMapel;
    private javax.swing.JTextField eNama1;
    private javax.swing.JTextField eNilai;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
