/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asuka-PC
 */
public class Frame5 extends javax.swing.JFrame {

    /**
     * Creates new form Frame5
     */
    public Frame5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brg2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        brg1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBayar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TAHasil = new javax.swing.JTextArea();
        diskon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        brg3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(brg2);
        brg2.setBounds(100, 80, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Pembayaran");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 10, 80, 14);

        jLabel8.setText("Barang 2");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 90, 60, 14);
        getContentPane().add(brg1);
        brg1.setBounds(100, 40, 140, 30);

        jLabel5.setText("Barang 1");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 50, 60, 14);

        btnBayar.setText("OK");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBayar);
        btnBayar.setBounds(120, 210, 47, 23);

        TAHasil.setColumns(20);
        TAHasil.setRows(5);
        jScrollPane3.setViewportView(TAHasil);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 250, 240, 140);
        getContentPane().add(diskon);
        diskon.setBounds(100, 160, 140, 30);

        jLabel9.setText("Diskon");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 170, 60, 14);
        getContentPane().add(brg3);
        brg3.setBounds(100, 120, 140, 30);

        jLabel7.setText("Barang 3");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 130, 60, 14);

        setBounds(0, 0, 297, 455);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        double barang1 = Double.parseDouble(brg1.getText());
        double barang2 = Double.parseDouble(brg2.getText());
        double barang3 = Double.parseDouble(brg3.getText());
        double potong = Double.parseDouble(diskon.getText());
        double harga = barang1+barang2+barang3;
        double apalah = potong/100;
        double total = harga-harga*apalah;


        TAHasil.setText("Barang 1 : "+barang1+"\n"+"Barang 2 : "+barang2+"\n"
                +"Barang 3 : "+barang3+"\n"+"Diskon : "+potong+"\n"+"Total Harga : "+harga+"\n"+"Total Bayar : \n"+String.valueOf(total));
    }//GEN-LAST:event_btnBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TAHasil;
    private javax.swing.JTextField brg1;
    private javax.swing.JTextField brg2;
    private javax.swing.JTextField brg3;
    private javax.swing.JButton btnBayar;
    private javax.swing.JTextField diskon;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
