/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asuka-PC
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        eNama1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eAbsen = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TA1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        rpl = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        cb4 = new javax.swing.JCheckBox();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        btnOK1 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 50, 40, 14);
        getContentPane().add(eNama1);
        eNama1.setBounds(100, 40, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Formulir");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 20, 50, 14);

        jLabel7.setText("Hobi");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 170, 40, 14);
        getContentPane().add(eAbsen);
        eAbsen.setBounds(100, 80, 140, 30);

        TA1.setColumns(20);
        TA1.setRows(5);
        jScrollPane3.setViewportView(TA1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 250, 240, 96);

        jLabel8.setText("Absen");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 90, 40, 14);

        rpl.setBackground(new java.awt.Color(153, 255, 153));
        buttonGroup1.add(rpl);
        rpl.setText("RPL");
        getContentPane().add(rpl);
        rpl.setBounds(90, 130, 60, 23);

        jRadioButton2.setBackground(new java.awt.Color(153, 255, 153));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("TKJ");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(160, 130, 93, 23);

        jLabel9.setText("Jurusan");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 130, 50, 14);

        cb4.setBackground(new java.awt.Color(153, 255, 153));
        cb4.setText("Designer");
        getContentPane().add(cb4);
        cb4.setBounds(200, 180, 80, 23);

        cb1.setBackground(new java.awt.Color(153, 255, 153));
        cb1.setText("Programming");
        getContentPane().add(cb1);
        cb1.setBounds(90, 160, 100, 23);

        cb2.setBackground(new java.awt.Color(153, 255, 153));
        cb2.setText("Animator");
        getContentPane().add(cb2);
        cb2.setBounds(90, 180, 90, 23);

        cb3.setBackground(new java.awt.Color(153, 255, 153));
        cb3.setText("Teknisi");
        getContentPane().add(cb3);
        cb3.setBounds(200, 160, 80, 23);

        btnOK1.setText("OK");
        btnOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK1);
        btnOK1.setBounds(40, 220, 70, 23);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(110, 220, 70, 23);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(180, 220, 70, 23);

        setBounds(0, 0, 312, 413);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK1ActionPerformed
        // TODO add your handling code here:
        String nama = eNama1.getText();
        String absen = eAbsen.getText();
        String jurusan;
        String hobi="";
        
        if(rpl.isSelected())
            jurusan ="RPL";
        else
            jurusan ="TKJ";
        
        if(cb1.isSelected())
            hobi+=cb1.getText()+" ";
        if(cb2.isSelected())
            hobi+=cb2.getText()+" ";
        if(cb3.isSelected())
            hobi+=cb3.getText()+" ";
        if(cb4.isSelected())
            hobi+=cb4.getText()+" ";
        TA1.append("Nama Siswa : "+nama+"\n"+"Absen : "+absen+"\n"+"Jurusan : "+jurusan+"\n"+"Hobi : "+hobi);
    }//GEN-LAST:event_btnOK1ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
       TA1.setText("");
       eNama1.setText("");
       eAbsen.setText("");
       cb1.setSelected(false);
       buttonGroup1.clearSelection();
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA1;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnOK1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JTextField eAbsen;
    private javax.swing.JTextField eNama1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rpl;
    // End of variables declaration//GEN-END:variables
}
